# The distance between the front and
# rear axle of the racecar
# rear axle of the racecar
wheelbase: 0.3302 # meters
# width of racecar
width: 0.2032 # meters
# The distance from the center of the
# rear axis (base_link) to the lidar
scan_distance_to_base_link: 0.275 # meters
# Lidar simulation parameters
scan_beams: 1080

wall_follow_topic: "/wall_follow"
wall_follow_idx: 5

gap_follow_topic: "/nav"
gap_follow_idx: 6

disparity_threshold: 1.5 # meters
disparity_buffer_angle: 0.05 # radians

rb: 0.36

kp: 0.9
ki: 0.1
kd: 0.1

sp: 0.7